version: 2

models:
  - name: top3_covid_stats_v1
    description: Model to extract stats for top 3 city based on severity index
    columns:
    - name: country
      description: Name of the country
      tests:
        - not_null
        - accepted_values:
            values: ['Chad', 'Burundi', 'Niger']
    - name: recovery_ratio
      description: People recovered in country divided by total recovered
      tests:
        - not_null
    - name: death_ratio
      description: People died in country divided by total died
      tests:
        - not_null
    - name: tests_ratio
      description: Tests done in country divided by total tests
      tests:
        - not_null

  - name: covid_africa_stats_v1
    description: Contains 3 stats for the whole data set i.e total recovered, median deaths, stdev total tests
    columns:
    - name: total_recovered
      description: Total number  of people recovered in the whole data
      tests:
      - not_null
    - name: median
      description: Median of total deaths in whole data
      tests:
      - not_null
    - name: std_deviation
      description: Standard deviation of total tests
      tests:
      - not_null

  - name: countries_with_si_v1
    description: Countries ranked with severity index
    columns:
    - name: Country
      description: Name of the country
      tests:
      - not_null
    - name: Total_Cases_1_mil_population
      description: Number of covid cases in 1  million population
      tests:
      - not_null
    - name: Deaths_1_mil_population_
      description: Number of covid deaths in 1 million population
      tests:
      - not_null
    - name: deaths_1_mil_rank
      description: Death rank of the country
      tests:
      - not_null
    - name: total_cases_1_mil_rank
      description: Total case rank of the country
      tests:
      - not_null
    - name: severity_index
      description: Severity index of the country (deaths_1_mil_rank * total_cases_1_mil_rank )
      tests:
      - not_null


       
  